### ISSUE TITLE
still active?

### ISSUE THREAD

**Issue by 4fthawaiian** [mcphee11/genesys-cloud-widget-features#1]
Hi there - I see that there have been no updates her for quite a while. I'm having some issues getting this working, and wondered if you can provide any advice.

**Comment by mcphee11** [comment]
@4fthawaiian This Repo has not had any updates in a long time due to nothing changing on it. But I personally do still have this example running in my dev environment and its working fine. What is the issue?

**Comment by 4fthawaiian** [comment]
thanks for your response! I consistently get a error when trying to run the docker container:

```
docker run -p 8080:8080 -p 8443:8443 -p 3000:3000 send_genesys:latest
Logging in to Genesys Cloud
Server ready on: http://localhost: 3000
(node:1) UnhandledPromiseRejectionWarning: Error: Bad Request
    at Request.callback (/usr/src/app/node_modules/superagent/lib/node/index.js:706:15)
    at /usr/src/app/node_modules/superagent/lib/node/index.js:916:18
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/superagent/lib/node/parsers/json.js:19:7)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

not really sure what this is pointing to :/

**Comment by mcphee11** [comment]
@4fthawaiian What request are you sending in? as based on the logging it logs in fine but i cant see what request you have sent it and its payload? I'm assuming the request is wrong hence the 400... You should have the config setup in the V2 widget to show whats its sending. 

As the error says it prob needs more catch blocks for better logging.

Also are you able to run it as a node app.js without making it into a Docker image??

Mine still runs 100% fine in my GCP Cloud Run and local Docker env on WSL2.

**Comment by 4fthawaiian** [comment]
Hey there - I haven't tried to send a request, as the app doesn't come up. I literally ran the docker command you see above, and got the output I pasted in. All I had done before that was to edit the `Dockerfile` with our credentials, and build the image like so:
```
docker build -t send_genesys:latest -f ./Dockerfile .
```

**Comment by 4fthawaiian** [comment]
And no, I get the same error when running it from node as well :/

**Comment by mcphee11** [comment]
Ok so I can still run it fine in my environment. Based on the fact that you cant even start the app.js or Docker image, I assume that you have not got the authentication correct in the OAuth2.0 Client Creds..... As I have not added any error checking other then the fact if checks if the IDs exist but not if they are valid. I tested this and if i have them wrong or without the required permissions/Roles i get the same error thrown. I have just added in some error checking into the code for this as well as a new log to show if it is "Authenticated". Ill push this code now please let me know your findings.

**Comment by 4fthawaiian** [comment]
hey there - got distracted, but back on top of this today. Your new code fixed something, because now I can authenticate. But when I try a `genesys.sendEmail` I still get an auth error:
```
    text: '{"error":"invalid_client","description":"authentication failed","error_description":"authentication failed"}\n',
```

any thoughts?

**Comment by 4fthawaiian** [comment]
here are the details for the id/secret I'm using:
**
![image](https://user-images.githubusercontent.com/1187264/168967789-940715cc-f078-4f3f-aead-4ef594f85feb.png)
**

**Comment by mcphee11** [comment]
Do you also have the required "roles" as to send an email this OAuth needs: "Conversation > Email > Create".... also the way this code works is it pulls the queueId & flowId from the config file like in my example. Ensure you also have these setup.

**Comment by 4fthawaiian** [comment]
<img width="740" alt="image" src="https://user-images.githubusercontent.com/1187264/168974237-477e7c7f-4a17-4c1f-93fd-3d1124325089.png">
Here are the roles that have been assigned (I don't have access to the UI, so I have to assume this is what you need) I have definitely checked the flowId and queueId as well

**Comment by 4fthawaiian** [comment]
Hi there - wondering if you have any further advice here. Also, I was wondering if we could possibly schedule some time to meet and go through this. I know you've met with Mark Grieve from our team before.  We're very eager to get this working on our end.

**Comment by mcphee11** [comment]
Those roles do not have the required permissions by default. You can look at the default permissions and what they include here: https://help.mypurecloud.com/articles/products-roles-and-permissions-list/ I would look at the permissions you have inside those roles in case they have been edited. if not (which i assume is the case) you will need to add some more roles that do include the permissions based on the features you are trying to use from this project.

**Comment by 4fthawaiian** [comment]
awesome - maybe we can spend some time in the upcoming session to review that :)

**Comment by mcphee11** [comment]
Now that its working ill close this issue.
