### ISSUE TITLE
Is something missing (a specific file)

### ISSUE THREAD

**Issue by Jonyb130** [mcphee11/genesys-cloud-widget-features#2]
Hi,

I get an error when trying to run it.
When I launch http://localhost:8080/ I get :
Cannot GET /
Is something missing ?
How should I rename the file exampleWidgetConfig.js ?

Thanks

**Comment by mcphee11** [comment]
While this still works most people have moved to the newer WebMessaging widget over this V2 widget. that asside though this app.js is designed to be middleware between the V2 Widget and Genesys Cloud to allow for the additional engage features from teh widget to work with cloud. based on your message i assume you are trying to view the nodejs server directly? the idea is you would configure the widget to talk to this nodejs server taht then talks to genesys cloud. the exampleWidgetConfig.js is a sample of how you need to config the widget config file on the website.

**Comment by Jonyb130** [comment]
Thank you for the feedback.

**Comment by mcphee11** [comment]
No problem if U still have issues please re open the issue, I'll close it for now. Cheers.
